#!/usr/bin/Rscript
# Plot normalized read depth for all yeast chromosomes
# Created 4/13/2017

args = commandArgs(T)
file = args[1]
data_I <- read.table(file,sep="\t",nrows=230218,skip=1)
data_II <- read.table(file,sep="\t",nrows=813184,skip=230219)
data_III <- read.table(file,sep="\t",nrows=316620,skip=1043403)
data_IV <- read.table(file,sep="\t",nrows=1531933,skip=1360023)
data_V <- read.table(file,sep="\t",nrows=576874,skip=2891956)
data_VI <- read.table(file,sep="\t",nrows=270161,skip=3468830)
data_VII <- read.table(file,sep="\t",nrows=1090940,skip=3738991)
data_VIII <- read.table(file,sep="\t",nrows=562643,skip=4829931)
#data_IX <- read.table(file,sep="\t",nrows=439888,skip=5392574)
#data_X <- read.table(file,sep="\t",nrows=745751,skip=5832462)
#data_XI <- read.table(file,sep="\t",nrows=666816,skip=6578213)
#data_XII <- read.table(file,sep="\t",nrows=1078177,skip=7245029)
#data_XIII <- read.table(file,sep="\t",nrows=924431,skip=8323206)
#data_XIV <- read.table(file,sep="\t",nrows=784333,skip=9247637)
#data_XV <- read.table(file,sep="\t",nrows=1091291,skip=10031970)
#data_XVI <- read.table(file,sep="\t",nrows=948066,skip=11123261)
d_I_pos <- as.numeric(data_I[,2])
d_I_norm <- as.numeric(data_I[,5])
d_II_pos <- as.numeric(data_II[,2])
d_II_norm <- as.numeric(data_II[,5])
d_III_pos <- as.numeric(data_III[,2])
d_III_norm <- as.numeric(data_III[,5])
d_IV_pos <- as.numeric(data_IV[,2])
d_IV_norm <- as.numeric(data_IV[,5])
d_V_pos <- as.numeric(data_V[,2])
d_V_norm <- as.numeric(data_V[,5])
d_VI_pos <- as.numeric(data_VI[,2])
d_VI_norm <- as.numeric(data_VI[,5])
d_VII_pos <- as.numeric(data_VII[,2])
d_VII_norm <- as.numeric(data_VII[,5])
d_VIII_pos <- as.numeric(data_VIII[,2])
d_VIII_norm <- as.numeric(data_VIII[,5])
#d_IX_pos <- as.numeric(data_IX[,2])
#d_IX_norm <- as.numeric(data_IX[,5])
#d_X_pos <- as.numeric(data_X[,2])
#d_X_norm <- as.numeric(data_X[,5])
#d_XI_pos <- as.numeric(data_XI[,2])
#d_XI_norm <- as.numeric(data_XI[,5])
#d_XII_pos <- as.numeric(data_XII[,2])
#d_XII_norm <- as.numeric(data_XII[,5])
#d_XIII_pos <- as.numeric(data_XIII[,2])
#d_XIII_norm <- as.numeric(data_XIII[,5])
#d_XIV_pos <- as.numeric(data_XIV[,2])
#d_XIV_norm <- as.numeric(data_XIV[,5])
#d_XV_pos <- as.numeric(data_XV[,2])
#d_XV_norm <- as.numeric(data_XV[,5])
#d_XVI_pos <- as.numeric(data_XVI[,2])
#d_XVI_norm <- as.numeric(data_XVI[,5])

png('chrI_dup_del.png')
plot(d_I_pos,d_I_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
dev.off()

png('chrII_dup_del.png')
plot(d_II_pos,d_II_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
dev.off()

png('chrIII_dup_del.png')
plot(d_III_pos,d_III_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
dev.off()

png('chrIV_dup_del.png')
plot(d_IV_pos,d_IV_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
dev.off()

png('chrV_dup_del.png')
plot(d_V_pos,d_V_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
dev.off()

png('chrVI_dup_del.png')
plot(d_VI_pos,d_VI_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
dev.off()

png('chrVII_dup_del.png')
plot(d_VII_pos,d_VII_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
dev.off()

png('chrVIII_dup_del.png')
plot(d_VIII_pos,d_VIII_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
dev.off()

#png('chrIX_dup_del.png')
#plot(d_IX_pos,d_IX_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
#dev.off()

#png('chrX_dup_del.png')
#plot(d_X_pos,d_X_norm,main="Normalized Read Depth vs. Position",xlab="Position",ylab="Normalized Read Depth",pch='.')
#dev.off()
